version: '3.8'

services:
  cownter-database:
    build: database
    image: cownter-database
    container_name: cownter-database
    volumes:
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql
    env_file:
      - database/.env
    ports:
      - "5432:5432"
    networks:
      - cownter-network
    restart: always

  cownter-api:
    build: api
    image: cownter-api
    container_name: cownter-api
    volumes:
      - ./api/resultados:/cownter/resultados    
    env_file:
      - api/.env
    ports:
      - "8000:80"
    networks:
      - cownter-network
    restart: always
    depends_on:
      - cownter-database

  cownter-frontend:
    build: frontend
    image: cownter-frontend
    container_name: cownter-frontend
    ports:
      - "5173:80"
    networks:
      - cownter-network
    restart: always
    depends_on:
      - cownter-api

networks:
  cownter-network: