// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmNwCbo7bJk-zC-ZzBgsW9tinqk5hVFaE',
    appId: '1:615218385080:web:8c2249e4a7731f573fa44d',
    messagingSenderId: '615218385080',
    projectId: 'cownter-1a190',
    authDomain: 'cownter-1a190.firebaseapp.com',
    storageBucket: 'cownter-1a190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmq9AbbwWUIU7r7cH78V8Lymb8Mvzu8gk',
    appId: '1:615218385080:android:8edbec53e2204f2a3fa44d',
    messagingSenderId: '615218385080',
    projectId: 'cownter-1a190',
    storageBucket: 'cownter-1a190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc3szuXP7Zk-HDsDVYYxSIGcSrxBT10s8',
    appId: '1:615218385080:ios:9557eba744e94d7a3fa44d',
    messagingSenderId: '615218385080',
    projectId: 'cownter-1a190',
    storageBucket: 'cownter-1a190.appspot.com',
    iosClientId: '615218385080-tcnfdmh1foe2760m1pcnkmegvi4alb90.apps.googleusercontent.com',
    iosBundleId: 'com.example.cownter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc3szuXP7Zk-HDsDVYYxSIGcSrxBT10s8',
    appId: '1:615218385080:ios:9557eba744e94d7a3fa44d',
    messagingSenderId: '615218385080',
    projectId: 'cownter-1a190',
    storageBucket: 'cownter-1a190.appspot.com',
    iosClientId: '615218385080-tcnfdmh1foe2760m1pcnkmegvi4alb90.apps.googleusercontent.com',
    iosBundleId: 'com.example.cownter',
  );
}
